package:
  name: q2-virsorter2
  version: {{ PLUGIN_VERSION }}

source:
  path: ..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - qiime2 {{ qiime2_epoch }}.*
    - q2-types {{ qiime2_epoch }}.*
    - prodigal
    - pyhmmer
    - screed
    - virsorter=2

test:
  imports:
    - q2_virsorter2
    - qiime2.plugins.virsorter2
  commands:
    - pytest --pyargs q2_virsorter2

about:
  home: https://github.com/bokulich-lab/q2-virsorter2
  license: BSD-3-Clause
  license_family: BSD
