{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-viromics
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - qiime2 {{ qiime2_epoch }}.*
    - q2-types {{ qiime2_epoch }}.*
    - prodigal
    - pyhmmer
    - screed
    - virsorter=2

test:
  requires:
    - coverage
    - pytest-cov
  imports:
    - q2_viromics
    - qiime2.plugins.viromics
  commands:
    - pytest --cov q2_viromics --cov-report xml:coverage.xml --pyargs q2_viromics

about:
  home: https://github.com/bokulich-lab/q2-viromics
  license: BSD-3-Clause
  license_family: BSD
